"""init

Revision ID: 43006efa818f
Revises: 
Create Date: 2026-05-14 10:42:56.416349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43006efa818f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_equipements_code'), 'equipements', ['code'], unique=True)
    op.alter_column('inspections', 'date_inspection',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('items', 'type',
               existing_type=mysql.ENUM('binaire', 'numerique'),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('admin', 'superviseur', 'technicien'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('admin', 'superviseur', 'technicien'),
               nullable=True)
    op.alter_column('items', 'type',
               existing_type=mysql.ENUM('binaire', 'numerique'),
               nullable=True)
    op.alter_column('inspections', 'date_inspection',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.drop_index(op.f('ix_equipements_code'), table_name='equipements')
    # ### end Alembic commands ###
