"""Add profile fields

Revision ID: b785afa4a92b
Revises: 43006efa818f
Create Date: 2026-05-31 14:14:42.132567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b785afa4a92b'
down_revision: Union[str, Sequence[str], None] = '43006efa818f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telephone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('adresse', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('ville', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ville')
    op.drop_column('users', 'adresse')
    op.drop_column('users', 'telephone')
    # ### end Alembic commands ###
