"""Add InspectionHistory

Revision ID: dec450f07653
Revises: d61df6faff9e
Create Date: 2026-06-01 14:27:30.496402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dec450f07653'
down_revision: Union[str, Sequence[str], None] = 'd61df6faff9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_history', sa.Column('data', sa.JSON(), nullable=True))
    op.drop_column('inspection_history', 'resultats_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_history', sa.Column('resultats_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.drop_column('inspection_history', 'data')
    # ### end Alembic commands ###
